layout tall

#launch --type=window --title=btop /opt/homebrew/bin/btop

launch --type=window --location=vsplit --title=fastfetch sh -c "/opt/homebrew/bin/fastfetch; exec zsh"

launch --type=window --location=hsplit --title=btm /opt/homebrew/bin/btm

